        ACCOUNTANT I,
        ACCOUNTANT II,
        ACTING MEDICAL DIRECTOR,
        ADMINISTRATIVE OFFICER I,
        ADMINISTRATIVE OFFICER II,
        ARCHITECT GRADE I,
        ASSISTANT DIRECTOR NURSING,
        ASSISTANT DIRECTOR OF ADMIN,
        ASSISTANT DIRECTOR PHARMACIST,
        ASSISTANT EXEC. OFFICER (GD),
        ASSISTANT SOC. WELFARE OFF.,]
        ASSITANT EXECUTIVE OFFICER 
        ASST. ANAESTHESIA TECHNICIAN
        ASST. CATERING OFFICER
        ASST. CHIEF ACCOUNTANT
        ASST. CHIEF AUDITOR
        ASST. CHIEF AUDITOR
        ASST. CHIEF CONF.SECRETARY
        ASST. CHIEF NURSE ANAESTHETICS
        ASST. CHIEF NURSING OFF. (ANAESTH)
        ASST. CHIEF NURSING OFFCER
        ASST. CHIEF NURSING OFFICER
        ASST. CHIEF PROC. OFFICER 
        ASST. CHIEF STATE COUNSEL
        ASST. CHIEF STATISTICAL OFF.
        ASST. CHIEF TECH.OFFICER
        ASST. CHIEF TECHNICALOFFICER
        ASST. DATA PROCESSING OFFICER
        ASST. DIRECTOR MEDICAL LAB.SCI.
        ASST. DIRECTOR NURSE TUTOR
        ASST. DIRECTOR NURSINGOFFICER
        ASST. DIRECTOR OF ADMIN
        ASST. DIRECTOR OF NURSING
        ASST. DIRECTOR OF PHYSIO
        ASST. DIRECTOR OF RADIOGRAP.
        ASST. DIRECTOR, FINANCE
        ASST. DIRECTOR, NURSING
        ASST. DIRECTOR, SOCIAL WLFR. SERV.
        ASST. EXEC.OFF.  (INFORMAT.)
        ASST. EXEC.OFF. I (G/DUTIES)
        ASST. NURSING OFFICER
        ASST. SOCIAL WELF. OFF GRD I
        ASST. STORE OFFICER
        ASST. TECH. OFF. (LAUNDRY)
        ASST.DIR.MED.LAB.SCI.
        ASST.DIR.NURSETUTOR
        ASST.DIRECTOR OF AUDIT
        ASST.DIRECTOR OF PHARMACY
        ASST.DIRECTOR, FINANCE
        ASST.NURSINGOFF. (ANAESTH)
        ASST.DIRECTOR  MEDICAL LAB. SCI.
        AUDITOR I
        AUDITOR II
        BIO-MEDICAL ENGINEERING I
        BIO-MEDICAL TECHNICIAN
        CATERING ASSISTANT
        CATERING OFFICER
        CHIEF  BIO. MED. ENGR.
        CHIEF ACCOUNTANT
        CHIEF ADMIN OFFICER
        CHIEF BIO-MEDICAL TECH I
        CHIEF CATERING OFFICER
        CHIEF CIVIL ENGINEER
        CHIEF CLERICAL OFFICER
        CHIEF EDUCATION OFFICER
        CHIEF ENGINEER (ELECT.)
        CHIEF ENVTAL HEALTH  ASST.
        CHIEF ENVTAL HEALTH ASST.
        CHIEF GRAPHIC ART ASST.
        CHIEF GRAPHIC ART OFFICER
        CHIEF HEALTH ASSISTANT
        CHIEF HEALTH ASSISTANT (ENVTAL)
        CHIEF HEALTH ASST
        CHIEF HEALTH ASST (PHYSIO)
        CHIEF INFORMATION OFFICER
        CHIEF INFORMATION ASST.
        CHIEF LIBRARY ASSISTANT
        CHIEF LIBRARY OFFICER
        CHIEF MOTOR DRIVER/MECHANIC
        CHIEF MOTOR DRIVER
        CHIEF MOTOR/DRIVER MECH. 
        CHIEF NURSE TUTOR
        CHIEF NURSING OFF. (CONTRACT)
        CHIEF NURSING OFFICER
        CHIEF NURSING OFFICER (B&P)
        CHIEF PHARMACIST
        CHIEF PROCUREMENT OFFICER 
        CHIEF SOC. WELF. ASST.
        CHIEF STORE KEEPER
        CHIEF TELEPHONE SUPERVISOR
        CHIEF  DRIVER/MECH
        CHIEF ADMIN OFFICER
        CHIEF ADMIN OFFICER
        CHIEF BIO. MED. TECHNICIAN
        CHIEF CATERING OFFICER
        CHIEF CLER. OFF.(ACCTS)
        CHIEF CLERICAL OFFICER
        CHIEF DRIVER/MECH
        CHIEF ENVTAL HEALTH OFF.
        CHIEF EXEC. OFF. (ACCTS)
        CHIEF EXECUTIVE OFFICER
        CHIEF HEALTH ASSISTANT
        CHIEF HEALTH ASST.
        CHIEF HEALTH ASST. (P/H)
        CHIEF LIBRARY  OFFICER
        CHIEF MED. LAB. TECH.
        CHIEF MED. LAB. ASST.
        CHIEF MEDICAL LAB. SCI.
        CHIEF MOTOR DRIVER
        CHIEF NURSE TUTOR
        CHIEF NURSING OFF. (ANAESTH)
        CHIEF NURSING OFFICER
        CHIEF PHARMACIST
        CHIEF PHYSIOTHERAPIST
        CHIEF REPORTER
        CHIEF STORES ASSISTANT
        CHIEF STORES OFFICER
        CHIEF TECHNICAL OFFICER
        CHIEF TELEPHONE SUP.
        CHIEF.CLERICAL OFFICER
        CIVIL ENGINEER I (CHEMICAL)
        CIVIL ENGINEER I (CIVIL)
        CLERICAL OFFICER I
        CLERICAL OFFICER II
        CLERICAL OFFICER
        CLINICAL INSTRUCTOR (BURNS)
        CONFIDENTIAL SEC. III
        CONFIDENTIAL SECRETARY  I
        CONFIDENTIAL SECRETARY II
        CONSULT RAD. SPECIAL GRD I
        CONSULT RADIOLOGIST
        CONSULT ANAESTH. SP. GRD I
        CONSULT. (FAMILY PHY) GRD II
        CONSULT. HAEMATOLOGIST
        CONSULT. OBSTETRICIAN
        CONSULT. ORTH. SURGEON. GRD II
        CONSULT. OTHOPEADIC SURG
        CONSULT. SPINE SURGEON
        CONSULT. ORTH. SURG. GD II
        CONSULT. ORTH. SURG. GRD I
        CONSULT. ORTH. SURG. GRD II
        CONSULT. ORTH. SURG. SP GD I.
        CONSULTANT (B&PS) GD II
        CONSULTANT (PLAST. SURG)
        CONSULTANT FAMILY PHYSICIAN
        CONSULTANT MAXILLOFACIAL
        CONSULTANT (ANAESTH.)
        CONSULTANT CARDIOLOGIST
        CONSULTANT ORTH. SURGEON 
        CONSULTANT ORTH. SURGEON SP.GD I
        CONSULTANT ORTH. SURGEON.
        CONSULTANT SP. GRD. I
        CRAFTSMAN
        CRAFTSMAN (LEATHER WORKS)
        CRAFTSMAN (TAILORING)
        DATA PROCESSING ASSISTANT
        DENTAL MEDICAL OFFICER I
        DENTAL TECHNICIAN
        DENTAL THERAPIST
        DEP.  DIRECTOR OF FINANCE
        DEP. DIRECTOR ENGINEERING
        DEP. DIRECTOR OF PHARMACY
        DEP. DIRECTOR OF RADIOLOGY
        DEP. DIRECTOR NURSE EDUC.
        DEP. DIR. MED. LAB. SCIENCE
        DEPUTY DIRECTOR NURSING 
        DIRECTOR OF ADMINISTRATION
        DIRECTOR OF PHARMACY
        EDUCATION OFFICER, II
        ELECTRICAL ENGINEERING I
        ENVIROMNENTAL HEALTH OFFICER
        ENVTAL HEALTH ASSISTANT 
        ENVTAL SENIOR ASST (P/H)
        ENVTAL SENIOR HEALTH ASSISTANT
        EXECUTIVE OFF. (G/D)
        EXECUTIVE OFFICER (ACCT)
        EXECUTIVE OFFICER (ACCTS)
        EXECUTIVE OFFICER (ACCTS.)
        EXECUTIVE OFFICER (G/D)
        FOREMAN
        FOREMAN (Bricklaying)
        FOREMAN (Carpentry)
        FOREMAN (Painting)
        FOREMAN (TAILORING)
        FOREMAN (Welding)
        FORESTRY OFFICER II
        HEAD COOK
        HEAD HEALTH ATTENDANT
        HEAD HEALTH ATTENDANT
        HEAD PORTER
        HEAD  HEALTH ATTENDANT
        HEAD  WASHERMAN
        HEAD COOK
        HEAD HEALTH ATENDANT
        HEAD HEALTH ATTD
        HEAD HEALTH ATTD (P/H)
        HEAD HEALTH ATTD.
        HEAD HEALTH ATTENDANT
        HEAD LAUNDRY MAN
        HEAD PORTER
        HEAD SECURITY GUARD
        HEAD WASHERMAN
        HEAD WASHERMAN
        HEALTH INFORM MGT TECH 
        HEALTH RECORD TECHNICIAN
        HEALTH RECORDS TECHNICIAN
        HEALTH RECORDS TECH.
        HIGH. EXECUTIVE OFF. (G/D)
        HIGH. HEALTH RECORDS TECHN.
        HIGH. PROSTH. & ORTHO.TECHN
        HIGH. TECH OFF. (METALL.) 
        HIGH. TECH. OFFICER (ELECT.)
        HIGH. TECH.OFF. (ELECTRICAL)
        HIGH.TECH. OFF. (BUILDING)
        HIGHER  ORTHOPAEDIC CAST TECH.
        HIGHER CATERING OFFICER
        HIGHER DENTAL TECHNOLOGIST
        HIGHER ENV. HEALTH SUPT.
        HIGHER ENVR.HEALTH ASSISTANT.
        HIGHER ENVTAL HEALTH TECH.
        HIGHER EXEC. OFF. (AUDIT)
        HIGHER EXEC. OFF. (INFOR.)
        HIGHER EXEC. OFFICER (ACCTS)
        HIGHER EXECUTIVE OFFICER (ACCTS)
        HIGHER EXECUTIVE OFF. (ACCTS)
        HIGHER FOREST SUPRTNDENT
        HIGHER HEALTH RECORDS TECH.
        HIGHER HEALTH RECORDS TECHN.
        HIGHER HEALTH RECORDS TECH.
        HIGHER LIBRARY OFFICER
        HIGHER MED. LAB. TECHNICIAN 
        HIGHER MEDICAL LAB. TECHNICIAN
        HIGHER NUTRITION OFFICER
        HIGHER ORTHO. CAST TECH.
        HIGHER ORTHOP. CAST TECH
        HIGHER ORTHOPAEDIC CAST TECH.
        HIGHER STATISTICAL OFFICER
        HIGHER STORE OFFICER
        HIGHER STORES OFFICER
        HIGHER TECHN. OFF. (TEXTILE)
        HIGHER TECHNICAL OFF. (CIVIL)
        HIGHER TECHNICAL OFF. (PLUMBING)
        HIGHER WORK SUPRERINTENDENT
        HIGHER WORKS SUPERINTENDENT
        HIGHER X-RAY TECHNICIAN
        HIGHER  HEALTH ASST (P/H)
        HIGHER HEALTH  ASSISTANT
        HIGHER HEALTH  ASST.
        HIGHER HEALTH ASSISTANT
        HIGHER HEALTH ASST 
        INFORMATION ASSISTANT
        INFORMATION OFFICER I
        INFORMATION OFFICER II
        JUNIOR RESIDENT
        JUNIOR RESIDENT (ANAESTH)
        JUNIOR RESIDENT (NEUROSURG.)
        JUNIOR RESIDENT DOCTOR II
        JUNIOR RESIDENT II
        JUNIOR RESIDENT II (BURNS & PLASTIC)
        JUNIOR RESIDENT II (LOCUM)
        JUNIOR RESIDENT II (O & G)
        JUNIOR RESIDENT II (ORTH.)
        JUNIOR RESIDENT II (PLASTIC & RECON.)
        LIBRARIAN
        LIBRARIAN II
        LIBRARIAN I
        LIBRARIAN II
        LIBRARY ASSISTANT
        MEDICAL LAB TECHINICIAN
        MEDICAL LAB. SCIENTIST
        MEDICAL LAB. TECHNICIAN
        MEDICAL OFFICER
        MOTOR DRIVER/MECHANIC II
        MOTOR-DRIVER/MECHANIC
        NURSE EDUCATION OFFICER, I
        NURSE TUTOR I
        NURSING OFFICER I
        NURSING OFFICER II
        NURSING OFFICER I
        ORTH.CAST.TECH
        ORTHOPAEDIC CAST TECH.
        ORTHOPAEDIC CAST TECHN
        PHARMACIST
        PHARMACY TECHNICIAN
        PHOTOGRAPHIC ASSISTANT
        PHYSIOTHERAPIST
        POST
        PRIN PHYSIO ASST
        PRIN.  X-RAY TECHNICIAN
        PRIN. CATERING OFFICER, I
        PRIN. EXEC. OFFICER (PROC.)
        PRIN. HEALTH RECORDS TECH. I
        PRIN. INFORMATION OFFICER
        PRIN. INFORMTN. MGT TECH. II
        PRIN. NUTRITION OFF. GD II
        PRIN. PROSTH. & ORTH. TECHN
        PRIN. SOCIAL WELFRAE OFFICER 
        PRIN. WORKS SUPRERINTENDENT I
        PRIN.BIO MED ENGINEER
        PRINC. CATERING OFFICER, II
        PRINC. CONF. SECRETARY II
        PRINC. ENVTAL HEALTH ASST
        PRINC. EXEC. OFF. II (ACCTS)
        PRINC. EXEC. OFFICER II, (ACCTS)
        PRINC. EXEC.OFF. II, (AUDIT)
        PRINC. HEALTH ASSISTANT
        PRINC. HIGH HEALTH REC.TECH.
        PRINC. INFORMATN. MGT. TECH. I
        PRINC. MED. LAB. SCI.
        PRINC. NURSING OFF. (ANAESTH)
        PRINC. PHYSIOTHERAPIST
        PRINC. STATISTICAL OFFICER II
        PRINC. EXEC. OFF. II (ACCTS)
        PRINC. EXEC. OFF. II, (ACCTS)
        PRINC. HEALTH ASST 
        PRINC. MEDICAL LAB. TECH. I
        PRINCIPAL  ACCOUNTANT
        PRINCIPAL  NURSING OFFCER 
        PRINCIPAL ADMIN OFFICER
        PRINCIPAL BIO. MED. TECH. I
        PRINCIPAL CATERING OFFICER II
        PRINCIPAL CONF. SECRETARY I
        PRINCIPAL CONF. SECRETARY II
        PRINCIPAL EXEC. OFFICER, II (G/D)
        PRINCIPAL EXEC.OFF. I (AUDIT)
        PRINCIPAL MEDICAL LAB. TECHN. I
        PRINCIPAL NURSE TUTOR
        PRINCIPAL NURSING OFFCER 
        PRINCIPAL PHARMACY TECH.
        PRINCIPAL PHARMACY TECH. I
        PRINCIPAL PHYSIOTHERAPIST
        PRINCIPAL RADIOGRAPHER
        PRINCIPAL STATE COUNSEL
        PRINCIPAL STORES OFFICER
        PRINCIPAL STORES OFFICER II
        PRINCIPAL X-RAY TECH I
        PRINCIPAL X-RAY TECH. I
        PRINCIPAL EXEC. OFF. I (ACCTS)
        PRINCIPAL EXEC. OFF. I (ACCTS)
        PRINCIPAL GRAPHIC ART OFF. I
        PRINCIPAL PHAMACIST
        PRINCIPAL PHARMACIST
        PROCUREMENT OFFICER II
        PROCUREMENT OFFICER II  (QS)
        PROGRAM ANALYST I
        PROGRAM ANALYST II
        RADIOGRAPHER
        SENIOR HEALTH ASST (P/H)
        SENIOR PROCUREMENT OFFICER
        SENIOR  EXEC. OFF. (AUDIT)
        SENIOR ADMIN. OFFICER
        SENIOR ADMINISTRATIVE OFFICER
        SENIOR AUDITOR
        SENIOR CATERING OFFICER
        SENIOR CLERICAL OFFICER
        SENIOR CLERICAL OFFICER
        SENIOR CONFIDENTIAL SECRETARY
        SENIOR CRAFTSMAN
        SENIOR CRAFTSMAN (L/WORKS)
        SENIOR CRAFTSMAN (LEATHER WORKS)
        SENIOR CRAFTSMAN (METAL WORKS)
        SENIOR CRAFTSMAN (PLANT)
        SENIOR CRAFTSMAN (Plumbing)
        SENIOR DATA PROC. OFF.
        SENIOR DATA PROC. OFF.
        SENIOR DENTAL OFFICER
        SENIOR DENTAL TECHNOLOGIST
        SENIOR ELECTRICAL ENGR
        SENIOR ENVTAL  HEALTH SUP.
        SENIOR EXEC. OFF. (ACCTS)
        SENIOR EXEC. OFF. (AUDIT)
        SENIOR EXECUTIVE OFF. (G/D)
        SENIOR FOREMAN
        SENIOR FOREMAN 
        SENIOR FOREMAN (Electrical)
        SENIOR FOREMAN (LEATHER)
        SENIOR FOREMAN (P&O)
        SENIOR FOREMAN (Plumbing)
        SENIOR FOREMAN (LEATHER WORK)
        SENIOR FORESTRY OFFICER
        SENIOR HEALTH  ASSISTANT
        SENIOR HEALTH  ATTENDANT
        SENIOR HEALTH RECORDS TECH.
        SENIOR INFORMATION ASST.
        SENIOR LIBRARIAN
        SENIOR MEDICAL LAB. SCIENTIST
        SENIOR MEDICAL OFFICER
        SENIOR MOTOR DRIVER/MECHANIC I
        SENIOR NURSING OFFICER
        SENIOR NURSING OFFCER 
        SENIOR NURSING OFFCER (ICN)
        SENIOR NURSING OFFICER
        SENIOR NURSING OFFICER  (ANAES)
        SENIOR OCCUP. THERAPY TECHN
        SENIOR ORTHO. CAST TECH.
        SENIOR PHARMACIST
        SENIOR PHARMACY TECH.
        SENIOR PHYSIOTHERAPIST
        SENIOR PROCUREMENT OFFICER
        SENIOR PROGRAM ANALYST
        SENIOR RADIOGRAPHER
        SENIOR REGISTRAR I
        SENIOR RESIDENT II
        SENIOR RESIDENT II (ORTH.)
        SENIOR STATISTICAL OFFICER
        SENIOR STORE OFFICER
        SENIOR STORES OFFICER
        SENIOR TECH. OFF. (SURVEY)
        SENIOR TELEPHONE OPERATOR
        SENIOR WORKS SUPRINTNDNT
        SENIOR X-RAY TECHNICIAN
        SENIOR FOREMAN
        SENIOR MEDICAL OFFICER
        SENIOR REGISTRAR II
        SENIOR RESIDENT I
        SENIOR RESIDENT I (ANAESTH).
        SENIOR RESIDENT II
        SNR ENV. HEALTH OFFICER
        SNR TECHNICAL OFF. (ENGRG)
        SNR WORKS SUPERINTENDENT
        SNR HEALTH ASSISTANT
        SNR HEALTH ASST (P/H)
        SNR HEALTH ASST (PHYSIO)
        SENIOR CONF. SECRETARY
        SENIOR ENVTAL HEALTH ASST.
        SENIOR MEDICAL LAB. TECHN.
        SENIOR PHYSIOTHERAPIST
        SENIOR REGISTRAR I, (NEURO.)
        SENIOR RESIDENT , II
        SENIOR HEALTH  ASSISTANT
        SENIOR HEALTH ATTENDANT
        SENIOR OCCUPATIONAL THERAPIST
        SENIOR OCCUPATIONAL T. TECH. II
        SENIOR HEALTH ASST (P/H)
        SOCIAL WELFARE ASSISTANT
        SOCIAL WELFARE OFFICER I
        SOCIAL WELFARE OFFICER II
        SOCIAL WORKER I
        SOCIAL WORKER II
        STAFF NURSE
        STATISTICAL ASST. GRADE I
        STATISTICAL OFFICER
        STATISTICAL OFFICER I
        STATISTICIAN
        STATISTICIAN I
        STATISTICIAN II
        STORE KEEPER
        STORES OFFICER
        TECH. OFF. CIVIL ENGINEERING
        TECHNICAL OFF. (BIO-MEDICALS)
        TECHNICAL OFFICER 
        TECHNICAL OFFICER (CIVIL)
        TRANSPORT OFFICER
        WORKS SUPRETENDENT
        X-RAY TECHNICIAN
        X-RAY ASST]
