# Generated by Django 4.1.7 on 2023-07-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_personaldetail_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
