# Generated by Django 4.1.7 on 2023-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_personaldetail_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='zone',
            field=models.CharField(blank=True, choices=[('North-East', 'North-East'), ('North-West', 'North-West'), ('North-Central', 'North-Central'), ('South-East', 'South-East'), ('South-West', 'South-West'), ('South-South', 'South-South')], max_length=300, null=True),
        ),
    ]
