# Generated by Django 4.1.7 on 2023-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_personaldetail_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='zone',
            field=models.CharField(blank=True, choices=[('NORTH-EAST', 'NORTH-EAST'), ('NORTH-WEST', 'NORTH-WEST'), ('NORTH-CENTRAL', 'NORTH-CENTRAL'), ('SOUTH-EAST', 'SOUTHE-EAST'), ('SOUTH-WEST', 'SOUTH-WEST'), ('SOUTH-SOUTH', 'SOUTH-SOUTH')], max_length=300, null=True),
        ),
    ]
