# Generated by Django 4.1.7 on 2023-07-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_governmentappointment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='qualification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
