# Generated by Django 4.1.7 on 2023-07-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_alter_governmentappointment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentappointment',
            name='department',
            field=models.CharField(blank=True, choices=[('INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY'), ('ACCOUNT', 'ACCOUNT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='zone',
            field=models.CharField(blank=True, choices=[('NORTH-EAST', 'NORTH-EAST'), ('NORTH-WEST', 'NORTH-WEST'), ('NORTH-CENTRAL', 'NORTH-CENTRAL'), ('SOUTH-EAST', 'SOUTHE-EAST'), ('SOUTH-WEST', 'SOUTH-WEST'), ('SOUTH-SOUTH', 'SOUTH-SOUTH')], max_length=300, null=True),
        ),
    ]
