# Generated by Django 4.1.7 on 2023-07-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_alter_governmentappointment_current_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentappointment',
            name='department',
            field=models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('ACCOUNT', 'ACCOUNT'), ('BIO-MEDICAL ENGINEERING', 'BIO-MEDICAL ENGINEERING'), ('CLINICAL SERVICES', 'CLINICAL SERVICES'), ('CATERING', 'CATERING'), ('DISCIPLINE', 'DISCIPLINE'), ('ENGINEERING', 'ENGINEERING'), ('INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY'), ('INTERNAL AUDIT', 'INTERNAL AUDIT'), ('LEGAL', 'LEGAL'), ('LIBRARY', 'LIBRARY'), ('MEDICAL RECORD', 'MEDICAL RECORD'), ('MEDICAL ILLUSTRATION', 'MEDICAL ILLUSTRATION'), ('NURSING EDUCATION', 'NURSING EDUCATION'), ('NURSING SERVICES', 'NURSING SERVICES'), ('PATHOLOGY', 'PATHOLOGY'), ('PHARMACY', 'PHARMACY'), ('PHYSIOTHERAPHY', 'PHYSIOTHERAPHY'), ('PROSTHETIC AND ORTHOTICS', 'PROSTHETIC AND ORTHOTICS'), ('PROCUMENT', 'PROCUMENT'), ('PUBLIC HEALTH', 'PUBLIC HEALTH'), ('OCCUPATIONAL THERAPHY', 'OCCUPATIONAL THERAPHY'), ('RADIOLOGY', 'RADIOLOGY'), ('SERVICOM', 'SERVICOM'), ('SOCIAL WELFARE', 'SOCIAL WELFARE'), ('STORE', 'STORE'), ('TELEPHONE', 'TELEPHONE'), ('TRANSPORT', 'TRANSPORT')], max_length=300, null=True),
        ),
    ]
